# Generated by Django 4.0.4 on 2022-06-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qline', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='final',
        ),
    ]
