# Generated by Django 4.0.4 on 2022-06-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comon_remove_case_final'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comon',
        ),
        migrations.AlterModelOptions(
            name='case',
            options={},
        ),
    ]
