# Generated by Django 4.0.4 on 2022-06-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_comon_alter_case_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
    ]
