# Generated by Django 4.0.4 on 2022-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_help_helpimage_new_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
