# Generated by Django 4.0.4 on 2022-05-30 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about_aboutimage_footer_footernumbers_footertwo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='FooterTwoNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumbers', models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='HelpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='help',
            name='image',
        ),
        migrations.AlterField(
            model_name='footertwo',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.DeleteModel(
            name='FooterNumbers',
        ),
        migrations.AddField(
            model_name='footertwonumbers',
            name='footers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneNumbers', to='main.footertwo'),
        ),
    ]
