# Generated by Django 4.0.4 on 2022-05-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_favorite_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite',
            new_name='favorites',
        ),
    ]
