# Generated by Django 4.0.4 on 2022-05-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_favorite_favorite_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorites',
            new_name='favorite',
        ),
    ]
