# Generated by Django 4.0.4 on 2022-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_favorites_favorite_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footertwo',
            old_name='number',
            new_name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='footertwo',
            name='whatsapp',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='FooterTwoNumbers',
        ),
    ]
