# Generated by Django 4.0.4 on 2022-05-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_number_footertwo_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertwo',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='footertwo',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='footertwo',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='footertwo',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='footertwo',
            name='whatsapp',
        ),
    ]
