# Generated by Django 4.0.4 on 2022-05-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_footertwo_insta_remove_footertwo_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertwo',
            name='allType',
            field=models.CharField(blank=True, choices=[('Whatsapp', 'whatsapp'), ('Email', 'email'), ('Instagram', 'instagram'), ('Telegram', 'telegram'), ('Phone', 'phone')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footertwo',
            name='web',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
