# Generated by Django 4.0.4 on 2022-05-31 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_footertwo_alltype_footertwo_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertwo',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='footertwo',
            name='allType',
            field=models.CharField(blank=True, choices=[('Whatsapp', 'whatsapp'), ('Email', 'email'), ('Instagram', 'instagram'), ('Telegram', 'telegram')], max_length=200, null=True),
        ),
    ]
