# Generated by Django 4.0.4 on 2022-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_footertwo_number_alter_footertwo_alltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertwo',
            name='web',
        ),
        migrations.AddField(
            model_name='footertwo',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footertwo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='footertwo',
            name='allType',
            field=models.CharField(choices=[('w', 'Whatsapp'), ('e', 'Email'), ('i', 'Instagram'), ('t', 'Telegram'), ('p', 'PhoneNumber')], max_length=100, null=True),
        ),
    ]
