# Generated by Django 4.0.4 on 2022-05-31 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_footertwo_web_footertwo_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footertwo',
            old_name='link',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='footertwo',
            name='allType',
        ),
        migrations.AddField(
            model_name='footertwo',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='footertwo',
            name='telegram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='footertwo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
